### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by kogren161** [tgorgdotcom/locast2plex#208] opened 2021-02-01 23:11 UTC
Has anyone seen this error?

Microsoft Windows [Version 10.0.17134.1304]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>C:\locast2plex\main.py
Initiating Locast2Plex v0.6.2
Opening and Verifying Configuration File.
C:\locast2plex\config\config.ini
C:\locast2plex\config.ini
Loading Configuration File: C:\locast2plex\config.ini
Tuner count set to 3
Server is set to run on  127.0.0.1:6077
UUID set to: jlkvvhot...
Getting user location...
Getting location via provided lat\lon coordinates.
Got location as Seattle - DMA 819 - Lat\Lon 47.608013\-122.33517
Logging into Locast using username k*****@*****.com...
Error in function login:
Invalid Locast Login Credentials. Exiting...

C:\Windows\system32>

The credentials haven't changed.

This just started last night, all was well before then.

**Comment by kogren161** [comment] 2021-02-02 22:53
I was having trouble logging in to Locast on my Roku, but that is working now.  But the setup that was working for about a month is now giving me the error above.  The Login Credentials in my config.ini are exactly the same as what works logging in to the website.  Any thoughts on what has changed?  Is Locast doing something different?

**Comment by kogren161** [comment] 2021-02-02 23:30
I downloaded the latest code, now it is working again. :)

**Comment by jcastilloalonso** [comment] 2021-02-10 06:02
Please close the issue if the problem is now fixed.

**Closed** 2021-02-13 14:32 UTC
